#!/bin/bash
for j in 1 3 5;
    do
    for i in 1 2 3 4 5 6 7 8 9 10;
        do
        for k in 1 2 3 4 5 6 7 8 9 10;
            do
	    for l in 1 2 5 7 10 25 50 75 100; 
		do
		python3 main_3wrobot.py --mode $j --ndots 20 --radius 5 --is_bash True --dt_bash $l --Nactor $k --pred_step_size $i --folder all_var;
 	    done
        done
    done
done
